version: '3.4'
services:
  web-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  mysql:
    container_name: twitch-tok-db
    restart: always
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=twitch-tok
      - MYSQL_USER=twitch-tok
      - MYSQL_PASSWORD=twitch-tok
      - MYSQL_DATABASE=twitch-tok
    ports:
    - "3308:3306"
  redis:
    container_name: twitch-tok-redis
    image: redis:alpine
    restart: always
    ports:
     - 6379:6379